pipeline {
     agent any
     stages {
          stage("Checkout") {
               steps {
                    git url: 'https://github.com/sainiravi26/qualibrate.git'
               }
          }
     }
}