pipeline {
     agent any
     
     tools{
        maven 'maven'
        jdk 'jdk8'
     }
     
     environment {
        VERSION = 'latest'
        PROJECT = 'qualibrate-service'
        IMAGE = 'qualibrate-service:latest'
        ECRURL = 'http://236587623411.dkr.ecr.eu-central-1.amazonaws.com'
        ECRCRED = 'ecr:eu-central-1:ecr'
    }
 
     stages {
          stage ("initialize") {
               steps {
                    sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                       '''
                }        
          }
          stage("Checkout") {
               steps {
                    git branch: 'master', url: 'https://github.com/sainiravi26/qualibrate.git'
               }
          }
          
          stage('Compile') {
                steps {
                    dir("qualibrate-service"){
                        echo "-=- compiling project -=-"
                        sh "mvn clean compile"
                    }
                }
          }
          
          stage('Unit tests') {
                steps {
                    dir("qualibrate-service"){
                        echo "-=- compiling project -=-"
                        sh "mvn clean install"
                    }
                }
          }
          
          stage('Version preparations'){
                steps{
                    script{
                        // calculate GIT lastest commit short-hash
                        gitCommitHash = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
                        shortCommitHash = gitCommitHash.take(7)
                        // calculate a sample version tag
                        // VERSION = shortCommitHash
                        // set the build display name
                        currentBuild.displayName = "#${BUILD_ID}-${VERSION}"
                        IMAGE = "$PROJECT:$VERSION"
                        sh 'cp ./qualibrate-service/target/qualibrate-service-0.0.1-SNAPSHOT.jar cd-pipeline'
                    }
                }
          }
          
          stage('Build Docker Image') {
                steps {
                    script{
                       // Build the docker image using a Dockerfile
                        docker.build("$IMAGE","cd-pipeline")
                    }
                }
          }
          
          stage('Run API tests') {
                steps {
                    script{
                        docker.image("$IMAGE").withRun('-p 7001:7001') {
                        timeout(15) {
                            waitUntil {
                                    sleep 10
                                    def r = sh script: "wget -q http://localhost:7001 -O /dev/null", returnStatus: true
                                    return r == 0
                                }
                            }
                            dir("tests") {
                                sh './run_newman.sh'
                            }
                        }
                    }
                }
          }

          stage('Push Docker Image to ECR') {
                steps{
                    script{
                        // login to ECR - for now it seems that that the ECR Jenkins plugin is not performing the login as expected. I hope it will in the future.
                           sh("eval \$(aws ecr get-login --region eu-central-1 --no-include-email | sed 's|https://||')")
                        // Push the Docker image to ECR
                        // docker.withRegistry(ECRURL, ECRCRED){
                           docker.withRegistry(ECRURL){
                            docker.image(IMAGE).push()
                        }
                    }
                }
          }
     }
}